#!/bin/bash

UPDATE_APP_KEY=false

# Si no está presente el .env, utilizo el que viene de ejemplo y seteo la vble para auto generar la APP_KEY
if [ ! -f "/var/www/backend/.env" ]; then
    cp "/var/www/backend/.env.example" "/var/www/backend/.env"
    UPDATE_APP_KEY=true
fi

# Instalo las dependencias de composer
composer install -d "/var/www/backend"

# Si la vble para setear la app_key estaba en true, la genero
if [ $UPDATE_APP_KEY ]; then
    php "/var/www/backend/artisan" key:generate --ansi
fi