#!/bin/bash

# Instalo las dependencias de composer
composer install -d "/var/www/backend"

# Si no está presente el .env, lo creo
if [ ! -f "/var/www/backend/.env" ]; then
    # Create .env file
    cat > "/var/www/backend/.env" << EOF
APP_NAME=demo
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://backend.demo.test

LOG_CHANNEL=single

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_DATABASE=arbil
DB_USERNAME=arbil
DB_PASSWORD=2522

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120

REDIS_CLIENT=predis
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
EOF

    # Genero la app_key
    php "/var/www/backend/artisan" key:generate --ansi
fi